### ISSUE TITLE
Swift 1.2 support

### ISSUE THREAD

**Issue by mkoppanen** [ReactKit/SwiftState#14]
There are currently several issues with the build after the latest Xcode update (6D520o). We are looking at these locally and probably have a patch during today. 

How are you handling backwards incompatible changes at the moment? After the updates the code will only compile with Swift 1.2 as there is no proper support for conditional compiling in the language.

**Comment by inamiy** [comment]
I just created `swift/1.2` branch, 
so I appreciate if you can send me patch to this branch.
I will keep current `master` as Swift 1.1 for a while.

**Comment by inamiy** [comment]
This issue is resolved in #16.
