### ISSUE TITLE
Example in Readme lacks MyEvent.

### ISSUE THREAD

**Issue by bootchk** [ReactKit/SwiftState#24]
I cut and pasted the example in the Readme into a project that references SwiftState framework.  It would not compile until 1) I switched to building for "iOS Device" and 2) I cut and pasted your example definition of MyEvent into the project.

Now I understand that the caller must define the MyEvent type.  But the example could be better.

Also, I don't understand how some of the StateMachine tests work because they also reference MyEvent type.  It is not clear to me how the tests found that type.  But I know little about XCTest.

**Comment by inamiy** [comment]
Yes, current README doesn't explain about `Event` handling very well, so I will revise it later.

> Also, I don't understand how some of the StateMachine tests work because they also reference MyEvent type. It is not clear to me how the tests found that type. But I know little about XCTest.

`MyEvent` can be found in test bundle (package), and it is automatically shared across the files in the bundle without explicitly writing C-style `#import "MyEvent.h"`.

**Comment by ileitch** [comment]
What's the intended use of Events? When would I use `addRouteEvent` instead of `addHandler`?

**Comment by inamiy** [comment]
Sorry for late reply.
I updated README.md and also bumped ver 3.0.0 for Swift 2 Support, 
so please check it :wink:
