### ISSUE TITLE
Allow Swift 2.0 code to be used by CocoaPods

### ISSUE THREAD

**Issue by adamyanalunas** [ReactKit/SwiftState#26]
Since #25 got merged in (thanks!) it'd be nice to have an updated podspec so I can use it in my apps. However, as Swift 2.0 isn't yet in production a branch would suffice so I can do something like: 

```
pod 'SwiftState', :git => 'git@github.com:ReactKit/SwiftState.git', :branch => 'swift-2.0'
```

What do you think, @inamiy?

**Comment by inamiy** [comment]
I think you can already use like this:

```
platform :osx, '10.10'
use_frameworks!

pod 'SwiftState', :git => 'https://github.com/ReactKit/SwiftState.git', :branch => 'swift/2.0'
```

Please be careful for branch name and OS platform (change to `:ios, '8.0'` if needed).
