### ISSUE TITLE
Can't build with Swift 2.0 on XCode7 beta5

### ISSUE THREAD

**Issue by dcunited001** [ReactKit/SwiftState#31]
When I try to build the `swift/2.0` branch on XCode7, I'm getting nearly a hundred errors about private class names.  I think what's happening is that the private type aliases are being misinterpreted by the swift compiler.  It's difficult to test this assumption because I'm getting so many build errors that I can't find the root of the type/alias dependencies.  Have you seen anything like this?

**Comment by dcunited001** [comment]
The messages I'm seeing look like this: `Type alias cannot be declared public because its underlying type uses an internal type.`

When I change the visibility of some of the aliases, this alleviates some of the compile errors.  And in particular, when I replace the `State` and `Event` aliases with `S` and `E`, this fixes a lot of errors.

**Comment by rhummelmose** [comment]
Having the same problem here.

**Comment by inamiy** [comment]
Sorry for late response.
I fixed it in f9a9a72d06f23d34d2f346fa194ee32ece3e3cce, so please check it :)

**Comment by dcunited001** [comment]
Thank you inamiy, I'll check it soon.  I asked on the swift-lang irc channel, but they were not aware of recent changes to typealias, so I wonder what was causing this.

**Comment by dcunited001** [comment]
Yup, it's building.  Thanks, @inamiy, SwiftState is going to help out a lot.
