### ISSUE TITLE
Machine.addHandler(transition: order: handler:) -> Disposable not working ?

### ISSUE THREAD

**Issue by toshi0383** [ReactKit/SwiftState#39]
I modified the basic test case as following and it's failing.
Any ideas to get rid of ?

```
    func testREADME_tryEvent()
    {
        var handlerCalled = false
        let machine = StateMachine<MyState, MyEvent>(state: .State0) { machine in

            // add 0 => 1 => 2
            machine.addRoutes(event: .Event0, transitions: [
                .State0 => .State1,
                .State1 => .State2,
            ])
            machine.addHandler(.Any => .Any) { _ in
                handlerCalled = true
            }
        }

        // initial
        XCTAssertEqual(machine.state, MyState.State0)

        // tryEvent
        machine <-! .Event0
        XCTAssertEqual(machine.state, MyState.State1)

        // tryEvent
        machine <-! .Event0
        XCTAssertEqual(machine.state, MyState.State2)

        // tryEvent (fails)
        machine <-! .Event0
        XCTAssertEqual(machine.state, MyState.State2, "Event0 doesn't have 2 => Any")

        XCTAssertTrue(handlerCalled) // Failure
    }
```

**Comment by inamiy** [comment]
In your example, you are registering event-based routes but attaching state-based handler, so it doesn't react to any event-triggering.

To fix this, please replace:

``` swift
// register handler for state-based transition, e.g. `machine <- .State0`
machine.addHandler(.Any => .Any) { ... }
```

to:

``` swift
// register handler for event-based transition, e.g. `machine <-! .Event0`
machine.addHandler(event: .Event0) { ... }
```

**Comment by toshi0383** [comment]
I thought it was working in previous version, though ?

**Comment by inamiy** [comment]
Yes, previous ver 3.x was working in that way (equal to `addEventHandler()`).
From ver 4.0.0, you need to use `machine.addHandler(event:)` instead.

P.S.
For reacting to _any_ events, you can use `machine.addHandler(event: .Any)`.

**Comment by inamiy** [comment]
Updated README.md in 84d4b42511c06f5fed95aeb5644b5f23d447c204.

**Comment by toshi0383** [comment]
👏
I see that. Thanks !

**Comment by philipbel** [comment]
Hello.

I find this behavior surprising. I was just playing with SwiftState, and wanted to model the state machine using a _mix_ of events and states. The idea being that I would attach handlers to the states, but send events to the machine to transition.

I understand this is not possible—I would have to choose events or states, but not both.
