### ISSUE TITLE
Request for improvement

### ISSUE THREAD

**Issue by sluramod** [ReactKit/SwiftState#40]
Currently, there are 2 types of handlers in StateMachine:
- based on event transition
- based on state transition

Suppose I want to have a handler that does not care how I got to from one state to another - it could be via state -> state transition or based on some event. 

It would be nice if there was a way to handle this scenario with a single handler.

**Comment by inamiy** [comment]
@sluramod 
Hi, thanks for your idea :sparkles::bulb::sparkles:
I have just implemented a rough sketch it in #41, so please take a look and tell me your thoughts!

**Comment by inamiy** [comment]
Done in #41!
