### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by bogosmer** [ReactKit/SwiftState#47]
I've got a question regarding iOS support.

Do you know if SwiftState will work if I include the code in an iOS project that has min deployment target of iOS 7? 

Thanks

**Comment by inamiy** [comment]
Hi. I haven't tried using this library in iOS 7, but since it is all written in pure Swift, just drag & drop the whole codes to your project (not using as dynamic framework) should work.

**Comment by bogosmer** [comment]
Cool, I would also think that it works. Will give it a go.

Thanks for the quick response!

**Comment by inamiy** [comment]
No problem :+1: 
Please let me know in case of that doesn't work.

**Comment by bogosmer** [comment]
Hi @inamiy 
We ran into problems on iOS 7. It seems to be because of this Swift 2.2 bug: https://bugs.swift.org/browse/SR-815

Don't know if we will try with Swift 2.1, but I will let you know if we do
