### ISSUE TITLE
Swift 3.0 compatible? 

### ISSUE THREAD

**Issue by aperritano** [ReactKit/SwiftState#49]

**Comment by phillco** [comment]
It's obviously an untenable solution long-term but I found as a Pods user, running Xcode's conversion wizard plus one manual fix (a ++ to a += 1) allowed it to work in a Swift 3.0 project.

**Comment by phillco** [comment]
It would be nice to add `@discardableResult` to the mutator functions, though -- otherwise you get lots of spurious "result is unused" warnings on the `addRoute` and `<-` calls.

**Comment by inamiy** [comment]
I created `swift/3.0` branch now.
Please check https://github.com/ReactKit/SwiftState/commit/8d2b4cadd3f57d0a376f500dd3d35459b8c13116.

### TODO
- [ ] Update README.md

**Comment by froimer** [comment]
Please, can you publish Swift 3 to master? Thanks.

**Comment by afinlayson** [comment]
Can you publish 3.0 to a new Pod version, as per usual practice.
I can create a pullrequest if you'll accept it.

**Comment by samskiter** [comment]
Is this swift 3.1 compatible too?

**Comment by inamiy** [comment]
Sorry for late response.
I will close this old issue.

@samskiter Sorry, Swift 3.1 is skipped and it now supports 4.0 in #59 .
