### ISSUE TITLE
onEntry and onExit handlers?

### ISSUE THREAD

**Issue by samskiter** [ReactKit/SwiftState#57]
From the README, I can see that you could construct state entry and exit handlers likes so:

 ```swift
// onExit handler
machine.addHandler(.State0 => .Any) { context in
    print("0 => 1")
}
```

 ```swift
// onEntry handler
machine.addHandler(.Any => .State0) { context in
    print("0 => 1")
}
```

But will these handlers be executed in the expected order? I don't really want to have to manage order through the int myself...

**Comment by inamiy** [comment]
Sorry for late response.
You can add `order: UInt8` to arrange the order.
If same value, it will be in added order.

**Comment by samskiter** [comment]
I mean that would the onExit be called before the onEntry of the next state?

**Comment by inamiy** [comment]
@samskiter 
That's right. 
If you don't add `order` when calling `addHandler`, handlers will be chosen in the following order:
https://github.com/ReactKit/SwiftState/blob/64d56f52e92a44f970bdd33a90e67d483279c675/Sources/Machine.swift#L560-L568
