### ISSUE TITLE
Support for Hierarchical State Machine?

### ISSUE THREAD

**Issue by Bouke** [ReactKit/SwiftState#8]
Hi @inamiy, I really like your take on state machines in Swift. I'm now running into an issue in which support for a Hierarchical State Machine would benefit the architectural design. For example, I have three states: A, B and C. A and B are two variants; and it is possible to go from either A or B to C. However, from C it is only possible to go to A. So I would need a handler (A, B) => C and C => A. However SwiftState doesn't allow me to create a handler (A, B) => C, so either I duplicate the handler (no good), or disregard the current state and add nil => C (but that also allows C => C, and a future D => C). As the states grow complexer, this would result in headaches; as adding yet another state would require re-evaluating all the current handlers.

**Comment by inamiy** [comment]
In ver 4.0.0, I refactored many codes and now **states with enums are supported** for hierarchical state machine.
Please see [Ver 4.0.0 Release Notes](https://github.com/ReactKit/SwiftState/releases/tag/4.0.0) and new [HierarchicalMachineTests.swift](https://github.com/ReactKit/SwiftState/blob/4.0.0/Tests/HierarchicalMachineTests.swift) for more info.
